version: "3.7"
services:
  awesome-example-api-mock-server:
    image: stoplight/prism:3
    ports:
      - "4040:4010"
    command: mock -h 0.0.0.0 /awesome-example-project-api.v1.yaml
    volumes:
      - ./awesome-example-project-api.v1.yaml:/awesome-example-project-api.v1.yaml
    networks:
      - openapi
networks:
  openapi:
